### PR TITLE
fix: set priorityClassName

### PR DESCRIPTION
**Pull request by mrclrchtr**
# Pull Request

## What? (description)
Set missing priorityClassName

## Why? (reasoning)
It's missing

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [x] you linted your code (`make lint`)
- [x] you linted your code (`make unit`)

make conformance error:
```
Error: failed to convert declarations: failed to convert commit policy: 1 error(s) decoding:

* 'gpg' expected a map, got 'bool'
```

### CODE REVIEW

**Comment by sergelogvinov** [comment]
Hi, thank you for this proposal, bitnami usually uses empty string by default.

https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml#L574

Maybe we should set like:
```yaml
priorityClassName: {{ default  "system-cluster-critical" .Values.priorityClassName }}
```

**Comment by mrclrchtr** [comment]
Yes, you're absolutely right. I was a bit stressed earlier and made a mistake.

**Comment by sergelogvinov** [comment]
Hi, can you:
* add  default value `priorityClassName: ""` to the values.yaml file
* add [DSO](https://github.com/apps/dco) - git commit -s  

Thanks.

**Comment by mrclrchtr** [comment]
Done. Thank you very much, sorry about the circumstances 😅

**Review by sergelogvinov — APPROVED** [review]

**Pull request merged**
