### PR TITLE
fix: prepend v to .Chart.AppVersion for image

### LINKED ISSUE #96: Image tag incorrect when deploying through helm
### Description

Latest version of the OCI chart (0.2.1) tries to pull the image "ghcr.io/siderolabs/talos-cloud-controller-manager:1.4.0" which doesn't exist. I've resolved it by changing "image.tag" to "v1.4.0".

### Environment

- Talos CCM version: 1.4.0
- Talos version: 1.5.3
- Kubernetes version: 1.27.6
- Platform: linux arm64

### PR DESCRIPTION
**Pull request by kanya-approve**
## What?

This is supposed to resolve #96. This will prepend v to the image. 

## Why?

Helm deployment fails because the "ghcr.io/siderolabs/talos-cloud-controller-manager:1.4.0" image does not exist.

## Acceptance
- [x] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [x] you ran conformance (`make conformance`)
- [x] you linted your code (`make lint`)
- [x] you linted your code (`make unit`)

### CODE REVIEW

**Comment by sergelogvinov** [comment]
Thank you for your PR.
I believe it was human error, than I did release procedure. 
I think the bast way to solve it in future to add test in github actions `.github/workflows/release-pre.yaml`.

make docs - knows the release TAG, and it can check the version in `Chart.yaml` file.

**Comment by kanya-approve** [comment]
What else should I add?

**Comment by sergelogvinov** [comment]
> What else should I add?

how about this `yq -i '.appVersion = "v1.2.3"'  charts/talos-cloud-controller-manager/Chart.yaml`

It will replace latest tag in Chart.yaml, if we set right version - the Chart.yaml would not change. 
here `.github/workflows/release-pre.yaml` we have 'Check' step -> `git diff --exit-code`

**Comment by kanya-approve** [comment]
Are you ok with the chart version reflecting as v{ACTUAL_VERSION} vs. ACTUAL_VERSION

**Comment by sergelogvinov** [comment]
> Are you ok with the chart version reflecting as v{ACTUAL_VERSION} vs. ACTUAL_VERSION

Hello, `git tag` already have `v` prefix, so I believe the best way to fix this typo is to check proper string in helm.appVersion.
Otherwise, we did not fix like this typo in the future... (appVersion == git-tag)

What do you think?

**Review by sergelogvinov — APPROVED** [review]

**Comment by sergelogvinov** [comment]
@kanya-approve Thank you.

**Pull request merged**
